INSERT INTO public.categories (id_category, name) VALUES (1, ' Alternative Music');
INSERT INTO public.categories (id_category, name) VALUES (2, ' Blues');
INSERT INTO public.categories (id_category, name) VALUES (3, ' Classical Music');
INSERT INTO public.categories (id_category, name) VALUES (4, ' Country Music');
INSERT INTO public.categories (id_category, name) VALUES (5, ' Dance Music');
INSERT INTO public.categories (id_category, name) VALUES (6, ' Easy Listening');
INSERT INTO public.categories (id_category, name) VALUES (7, ' Electronic Music');
INSERT INTO public.categories (id_category, name) VALUES (8, ' European Music');
INSERT INTO public.categories (id_category, name) VALUES (9, ' Hip Hop');
INSERT INTO public.categories (id_category, name) VALUES (10, ' Indie Pop');
INSERT INTO public.categories (id_category, name) VALUES (11, ' Inspirational');
INSERT INTO public.categories (id_category, name) VALUES (12, ' Asian Pop');
INSERT INTO public.categories (id_category, name) VALUES (13, ' Jazz');
INSERT INTO public.categories (id_category, name) VALUES (14, ' Latin Music');
INSERT INTO public.categories (id_category, name) VALUES (15, ' New Age');
INSERT INTO public.categories (id_category, name) VALUES (16, ' Opera');
INSERT INTO public.categories (id_category, name) VALUES (17, ' Pop');
INSERT INTO public.categories (id_category, name) VALUES (18, ' R&B');
INSERT INTO public.categories (id_category, name) VALUES (19, ' Reggae');
INSERT INTO public.categories (id_category, name) VALUES (20, ' Rock');
INSERT INTO public.categories (id_category, name) VALUES (21, ' Singe');
INSERT INTO public.categories (id_category, name) VALUES (22, ' World Music');